"""Writes docs/play-store/LISTING.md — every Google Play store text in one place.

    python docs/play-store/build_listing.py

The texts themselves live in fastlane/metadata/android/<locale>/ (the files
fastlane uploads); this script only collects them for copy-and-paste.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
META = ROOT / "fastlane/metadata/android"
OUT = Path(__file__).with_name("LISTING.md")
REPO = "https://github.com/kalipsers/TunnelKey/blob/main/"

LOCALES = [("en-US", "English (United States) — default"), ("sk", "Slovak — translation")]


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8").rstrip("\n")


def version() -> tuple[str, str]:
    gradle = (ROOT / "android/app/build.gradle.kts").read_text(encoding="utf-8")
    code = re.search(r"versionCode = (\d+)", gradle).group(1)
    name = re.search(r'versionName = "([^"]+)"', gradle).group(1)
    return code, name


def fence(text: str) -> str:
    return "```text\n" + text + "\n```"


def main() -> None:
    code, name = version()
    lines = [
        "# Google Play listing — Tunnelkey",
        "",
        "<!-- Generated by docs/play-store/build_listing.py from fastlane/metadata/android. Don't edit by hand. -->",
        "",
        "Everything to paste into the Play Console, in one place. Step-by-step console",
        "answers (data safety, content rating, VPN declaration, …) are in",
        "[README.md](README.md).",
        "",
        "## App details",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Package name | `com.proitservices.tunnelkey` |",
        f"| Current version | {name} (version code {code}) |",
        "| Publisher | ProIT services |",
        "| Category | Tools |",
        "| Contact email | develop@pro-it.sk |",
        "| Website | https://github.com/kalipsers/TunnelKey |",
        "| Privacy policy | https://kalipsers.github.io/TunnelKey/privacy-policy.html |",
        "| Price | Free, no ads, no in-app purchases |",
        "",
    ]
    for loc, label in LOCALES:
        d = META / loc
        notes = d / "changelogs" / f"{code}.txt"
        full = read(d / "full_description.txt")
        lines += [
            f"## {label}",
            "",
            f"### App name ({len(read(d / 'title.txt'))}/30)",
            "",
            fence(read(d / "title.txt")),
            "",
            f"### Short description ({len(read(d / 'short_description.txt'))}/80)",
            "",
            fence(read(d / "short_description.txt")),
            "",
            f"### Full description ({len(full)}/4000)",
            "",
            "Play renders `<b>…</b>` as bold.",
            "",
            fence(full),
            "",
        ]
        if notes.exists():
            lines += [f"### Release notes for version code {code} ({len(read(notes))}/500)", "", fence(read(notes)), ""]
        shots = sorted((d / "images/phoneScreenshots").glob("*.png"))
        lines += [
            "### Graphics",
            "",
            "| Asset | File |",
            "|-------|------|",
            f"| App icon 512×512 | [{loc}/images/icon.png]({REPO}fastlane/metadata/android/{loc}/images/icon.png) |",
            f"| Feature graphic 1024×500 | [{loc}/images/featureGraphic.png]({REPO}fastlane/metadata/android/{loc}/images/featureGraphic.png) |",
        ]
        lines += [
            f"| Phone screenshot {s.stem} (1080×2160) | [{loc}/images/phoneScreenshots/{s.name}]({REPO}fastlane/metadata/android/{loc}/images/phoneScreenshots/{s.name}) |"
            for s in shots
        ]
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
